config/routes.rb
Rails.application.routes.draw do
  resources :campos
  post 'campos/buscar'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/campo.rb
class Campo < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
    userName: 'A',
    description: 'B',
    
}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/campos_controller.rb
class CamposController < ApplicationController
  before_action :set_campo, only: %i[ show edit update destroy ]

  # GET /campos or /campos.json
  def index
    #Paginacion realizada con la gema pagy
  @pagy, @campos =pagy(Campo.all,items:10)
  #Buscador, lo hice agregando la gema pg_search con la posibilidad de buscar por userName y descripcion.
  @q= params[:query_text]
  print "*******" 
  print @q 
    print"********"
  if params[:query_text].present?
    @campos = @campos.search_full_text(params[:query_text])
    
  end

end
  # GET /campos/1 or /campos/1.json
  def show
  end

  # GET /campos/new   le voy a enviar una instancia con parametros 
  def new
    @campo = Campo.new
  end

  def buscar
    
  end

  # GET /campos/1/edit
  def edit
  end

  # POST /campos or /campos.json
  def create
    @campo = Campo.new(campo_params)

    respond_to do |format|
      if @campo.save
        format.html { redirect_to campo_url(@campo), notice: "Creado con éxito." }
        format.json { render :show, status: :created, location: @campo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campos/1 or /campos/1.json
  def update
    respond_to do |format|
      if @campo.update(campo_params)
        format.html { redirect_to campo_url(@campo), notice: "Campo was successfully updated." }
        format.json { render :show, status: :ok, location: @campo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campos/1 or /campos/1.json
  def destroy
    @campo.destroy

    respond_to do |format|
      format.html { redirect_to campos_url, notice: "Destruido con exito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campo
      @campo = Campo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campo_params
      params.require(:campo).permit(:userName, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/views/campos/_campo.html.erb
<%
=begin%>
 <div id="<%= dom_id campo %>">
  <p>
    <strong>Usuario:</strong>
    <%= campo.userName %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= campo.description %>
  </p>

</div> 
<%
=end%>

<div class="card "  id="<%= dom_id campo %>">
  <div class="card-body">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
    <h6 class="card-subtitle mb-2 text-body-secondary fw-semibold">Usuario:</h6>
    <br>
    <h4 class="card-subtitle mb-2 text-primary">@ <%= campo.userName %></h4>
    </li>
    <br>
    <li class="list-group-item">
    <p class="card-text fw-light text-body-secondary fw-semibold">Descripción: </p>
    <p> 
    - <%= campo.description %>
    </p> 
    </li>
  </ul>
  </div>
</div>

app/views/campos/_form.html.erb
<%= form_with(model: campo) do |form| %>
  <% if campo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campo.errors.count, "error") %> prohibited this campo from being saved:</h2>

      <ul>
        <% campo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campos/buscar.html.erb
<h1> hola</h1>

app/views/campos/edit.html.erb
<h1>Editing campo</h1>

<%= render "form", campo: @campo %>

<br>

<div class="text-decoration-underline">
  <%= link_to "Muestra el post", @campo %> |
  <%= link_to "volver", campos_path %>
</div>

app/views/campos/index.html.erb
<div class="container">

<p style="color: green"><%= notice %></p>

<nav class="navbar bg-secondary-subtle text-emphasis-secondary text-white d-block p-2 ">
  <div class="container-fluid">
  <span class="badge bg-primary">

<h1>Twitter</h1>
</span>
    <form class="d-flex" role="search">
      <%=form_with url: campos_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: 'Buscador', value: params[ :query_text] %>
        <button class="btn btn-sm btn btn-primary text-white" type="button"><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>Buscar</button>
      <%end%>
    </form>
  </div>
</nav>

<div class="text-primary-emphasis">




<%= link_to "Volver a los post", campos_path %> 


</div>

<br>

<div  id="campos">
  <% @campos.each do |campo| %>
    <%= render campo %>
    <p class="text-secondary-emphasis">
      <%= link_to "Muestra este post", campo %>
    </p>
  <% end %>
</div>

<div>
<%= link_to "Nuevo post", new_campo_path %>
</div>
<br>
<%== pagy_bootstrap_nav(@pagy) %>
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
<br>
</div>

app/views/campos/new.html.erb
<h1 class="text-primary-emphasis">Twitter</h1>

<%= render "form", campo: @campo %>

<br>

<div class="text-decoration-underline">
  <%= link_to "Volver", campos_path %>
</div>

app/views/campos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campo %>

<div class="text-decoration-underline">
  <%= link_to "Edita este campo", edit_campo_path(@campo) %> |
  <%= link_to "Volver", campos_path %>

  <%= button_to "Elminar post", @campo, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>